export const SET_USER_LOGIN_DATA = "SET_USER_LOGIN_DATA";
export const REMOVE_USER_LOGIN_DATA = "REMOVE_USER_LOGIN_DATA";

export const SET_SOCKET = "SET_SOCKET";
export const REMOVE_SOCKET = "REMOVE_SOCKET";

export const SET_CHANNEL_DATA = "SET_CHANNEL_DATA";
export const REMOVE_CHANNEL_DATA = "REMOVE_CHANNEL_DATA";

export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";

export const ADD_CONVERSATIONS = "ADD_CONVERSATIONS";
