export const SET_USER_LOGIN_DATA = "SET_USER_LOGIN_DATA";
export const REMOVE_USER_LOGIN_DATA = "REMOVE_USER_LOGIN_DATA";

export const SET_SOCKET = "SET_SOCKET";
export const REMOVE_SOCKET = "REMOVE_SOCKET";
