const QUERY_KEYS = {
  REGISTER: "REGISTER",
  VERIFYEMAIL: "VERIFYEMAIL",
  LOGIN: "LOGIN",
  VERIFYLOGIN: "VERIFYLOGIN",
  CHANNELCREATE: "CHANNELCREATE",
  LISTCHANNEL: "LISTCHANNEL",
};

export default QUERY_KEYS;
